name: Build, export and deploy info page

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Export
        run: npx npx nx build presenter-competitor --configuration=production --baseHref=/shorttrack-app/

      - name: Setup GitHub pages
        uses: actions/configure-pages@v2

      - name: Upload compiled artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/apps/presenter-competitor'

      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v1
