name: Build and push to dockerhub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: nrwl/nx-set-shas@v3
    - run: npm ci

    - name: Build app
      run: npx nx run gcpv-lynx-export:docker-build

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: gilliangoud
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      uses: docker/cli@v2
      with:
        command: push
        args: docker.io/gilliangoud/gcpv-lynx-export:latest

